### ISSUE TITLE
Clicking on PDF link in Arxiv abs page redirects back to the abs page

### ISSUE THREAD

**Issue by gokul-uf** [imurray/redirectify#7] opened 2018-03-09 22:38 UTC
The issue is as stated above.
I'm using Chrome on Ubuntu 16.04

**Comment by gokul-uf** [comment] 2018-03-09 22:42
Seems like same issue with NIPS and OpenReview as well. 
I used the examples from `README.md` to test this

**Comment by imurray** [comment] 2018-03-10 07:35
Thanks for the report. Are you opening in a new tab? If so, that's issue #1. I now think there might be an ugly work-around to that issue, and will sort it out when I find a moment.

If you are doing a normal left-click on the link, I can't reproduce (I am also on Ubuntu 16.04). Perhaps give me the version number of Chrome (and whether Chrome or Chromium?) and any other precise details.

**Comment by gokul-uf** [comment] 2018-03-11 18:34
Chrome Version: `Version 65.0.3325.146 (Official Build) (64-bit)`
I'm doing a normal left-click on the abs page and still see this issue.

These are the other extensions I've installed
1. Adblock Plus
2. arXiv title fixer
3. Google Docs offline
4. Google Scholar buttion
5. Librarian for arXiv | Fermat's Library
6. Streak CRM for Gmail
7. Twitter Demetricator
8. Unpaywall
9. YoutubeTutor

I don't think any of the above would interfere with redirectify

**Comment by imurray** [comment] 2018-03-11 19:22
Could you try with a clean profile? `chrome --user-data-dir=/tmp/delme`

If that fixes it, if you could bisect what the interaction is, that would be great. If that doesn't fix it, would you be prepared to run an augmented version and give me some debug information? I can insert lots of `console.log()` lines in the extension and ask you to run a version I send you.

Unfortunately I didn't have time this weekend to write the version that works around the new tab issue. It's possible that could fix things. But that you're having unexpected problems with the current versions actually makes me more nervous about releasing a more complicated version. Any help working out what's going on would be appreciated.

**Comment by gokul-uf** [comment] 2018-03-12 14:47
Some updates:
1. Reinstalling on the clean profile, the extension works as advertised :)
2. I tried disabling addons one by one and trying, issue still persists on the normal profile. I'm not sure what you mean by "bisect the interaction" though.


I'd be happy to help you with the debug info.

**Comment by imurray** [comment] 2021-03-06 19:36
I'm going to close this as I can't reproduce. If you get any closer to working out the problem, or if anyone else has this problem, then feel free to re-open.

**Closed as completed by imurray** 2021-03-06 19:36 UTC
Labels: question
